name: 'NiFi Flow CI/CD'
description: 'CI/CD actions for Apache NiFi flows using nipyapi CLI'
author: 'Chaffelson'

inputs:
  command:
    description: 'Command: ensure-registry, deploy-flow, start-flow, stop-flow, cleanup, configure-params, get-status, change-version, revert-flow, purge-flowfiles, export-flow-definition, import-flow-definition, list-registry-flows, get-versions, get-diff'
    required: true

  # NiFi Connection
  nifi-api-endpoint:
    description: 'NiFi API endpoint URL'
    required: true
  nifi-username:
    description: 'NiFi username'
    required: false
    default: ''
  nifi-password:
    description: 'NiFi password'
    required: false
    default: ''
  nifi-bearer-token:
    description: 'NiFi bearer token (alternative to username/password)'
    required: false
    default: ''
  nifi-verify-ssl:
    description: 'Verify SSL certificates'
    required: false
    default: 'true'

  # Registry configuration
  registry-token:
    description: 'PAT for Git repository access (GitHub or GitLab)'
    required: false
    default: ''
  registry-repo:
    description: 'Repository in owner/repo format'
    required: false
    default: ''
  registry-client-name:
    description: 'Name for the registry client'
    required: false
    default: ''
  registry-client-id:
    description: 'ID of the registry client'
    required: false
    default: ''
  repository-path:
    description: 'Path within repository'
    required: false
    default: ''

  # Flow configuration
  bucket:
    description: 'Bucket containing the flow'
    required: false
    default: ''
  flow:
    description: 'Flow name'
    required: false
    default: ''
  branch:
    description: 'Branch to deploy from'
    required: false
    default: ''
  version:
    description: 'Version to deploy'
    required: false
    default: ''

  # Process group operations
  process-group-id:
    description: 'ID of the Process Group'
    required: false
    default: ''

  # Parameters
  parameters:
    description: 'JSON object of parameters'
    required: false
    default: ''

  # Logging control
  log-level:
    description: 'Log level: ERROR, WARNING (default), INFO, DEBUG'
    required: false
    default: 'WARNING'

  # Export/Import flow definition
  file-path:
    description: 'File path for export/import operations'
    required: false
    default: ''
  parent-id:
    description: 'Parent process group ID for import operations'
    required: false
    default: ''
  export-mode:
    description: 'Export format: json or yaml'
    required: false
    default: 'json'

  # List registry flows options
  detailed:
    description: 'Include full details in list-registry-flows output'
    required: false
    default: 'false'

  # Stop/Cleanup options (safe defaults - explicit opt-in for destructive operations)
  disable-controllers:
    description: 'Disable controller services (for stop-flow, needed before deletion)'
    required: false
    default: 'false'
  delete-parameter-context:
    description: 'Delete parameter context during cleanup (for CI/CD full cleanup)'
    required: false
    default: 'false'
  force:
    description: 'Force deletion even with queued FlowFiles'
    required: false
    default: 'false'

outputs:
  # ensure-registry outputs
  registry-client-id:
    description: 'ID of the registry client'
    value: ${{ steps.run.outputs['registry-client-id'] }}
  registry-client-name:
    description: 'Name of the registry client'
    value: ${{ steps.run.outputs['registry-client-name'] }}

  # deploy-flow outputs
  process-group-id:
    description: 'ID of the deployed Process Group'
    value: ${{ steps.run.outputs['process-group-id'] }}
  process-group-name:
    description: 'Name of the deployed Process Group'
    value: ${{ steps.run.outputs['process-group-name'] }}
  deployed-version:
    description: 'Version deployed'
    value: ${{ steps.run.outputs['deployed-version'] }}

  # start-flow outputs
  started:
    description: 'Whether the flow was started'
    value: ${{ steps.run.outputs.started }}

  # stop-flow outputs
  stopped:
    description: 'Whether the flow was stopped'
    value: ${{ steps.run.outputs.stopped }}

  # get-status outputs
  state:
    description: 'Current state of the process group'
    value: ${{ steps.run.outputs.state }}
  running-processors:
    description: 'Number of running processors'
    value: ${{ steps.run.outputs['running-processors'] }}
  enabled-controllers:
    description: 'Number of enabled controller services'
    value: ${{ steps.run.outputs['enabled-controllers'] }}
  version-state:
    description: 'Version control state (UP_TO_DATE, LOCALLY_MODIFIED, etc)'
    value: ${{ steps.run.outputs['version-state'] }}

  # configure-params outputs
  parameters-updated:
    description: 'Whether parameters were updated'
    value: ${{ steps.run.outputs['parameters-updated'] }}

  # change-version outputs
  previous-version:
    description: 'Previous version before change'
    value: ${{ steps.run.outputs['previous-version'] }}
  new-version:
    description: 'New version after change'
    value: ${{ steps.run.outputs['new-version'] }}

  # revert-flow outputs
  reverted:
    description: 'Whether the flow was reverted'
    value: ${{ steps.run.outputs.reverted }}

  # purge-flowfiles outputs
  purged:
    description: 'Whether flowfiles were purged'
    value: ${{ steps.run.outputs.purged }}
  connections-purged:
    description: 'Number of connections purged'
    value: ${{ steps.run.outputs['connections-purged'] }}

  # cleanup outputs
  deleted:
    description: 'Whether the process group was deleted'
    value: ${{ steps.run.outputs.deleted }}
  deleted-name:
    description: 'Name of the deleted process group'
    value: ${{ steps.run.outputs['deleted-name'] }}

  # export-flow-definition outputs
  file-path:
    description: 'Path to exported file'
    value: ${{ steps.run.outputs['file-path'] }}
  format:
    description: 'Export format (json/yaml)'
    value: ${{ steps.run.outputs.format }}

  # import-flow-definition outputs
  source:
    description: 'Source of import (file/string)'
    value: ${{ steps.run.outputs.source }}
  parent-id:
    description: 'Parent process group ID'
    value: ${{ steps.run.outputs['parent-id'] }}

  # list-registry-flows outputs
  flow-count:
    description: 'Number of flows found in bucket'
    value: ${{ steps.run.outputs['flow-count'] }}
  flows:
    description: 'JSON array of flow information'
    value: ${{ steps.run.outputs.flows }}

  # get-versions outputs
  current-version:
    description: 'Currently deployed version'
    value: ${{ steps.run.outputs['current-version'] }}
  version-count:
    description: 'Number of versions available'
    value: ${{ steps.run.outputs['version-count'] }}
  versions:
    description: 'JSON array of version metadata'
    value: ${{ steps.run.outputs.versions }}

  # get-diff outputs
  modification-count:
    description: 'Number of modified components'
    value: ${{ steps.run.outputs['modification-count'] }}
  modifications:
    description: 'JSON array of modification details'
    value: ${{ steps.run.outputs.modifications }}

  # Common output
  success:
    description: 'Whether the command succeeded'
    value: ${{ steps.run.outputs.success }}

runs:
  using: 'composite'
  steps:
    - name: Install nipyapi CLI
      shell: bash
      run: pip install -q "nipyapi[cli]>=1.2.0"

    - name: Run command
      id: run
      shell: bash
      env:
        NIFI_API_ENDPOINT: ${{ inputs.nifi-api-endpoint }}
        NIFI_USERNAME: ${{ inputs.nifi-username }}
        NIFI_PASSWORD: ${{ inputs.nifi-password }}
        NIFI_BEARER_TOKEN: ${{ inputs.nifi-bearer-token }}
        NIFI_VERIFY_SSL: ${{ inputs.nifi-verify-ssl }}
        GH_REGISTRY_TOKEN: ${{ inputs.registry-token }}
        NIFI_REGISTRY_REPO: ${{ inputs.registry-repo || github.repository }}
        NIFI_REGISTRY_CLIENT_NAME: ${{ inputs.registry-client-name }}
        NIFI_REGISTRY_CLIENT_ID: ${{ inputs.registry-client-id }}
        NIFI_REPOSITORY_PATH: ${{ inputs.repository-path }}
        NIFI_BUCKET: ${{ inputs.bucket }}
        NIFI_FLOW: ${{ inputs.flow }}
        NIFI_FLOW_BRANCH: ${{ inputs.branch }}
        NIFI_TARGET_VERSION: ${{ inputs.version }}
        NIFI_PROCESS_GROUP_ID: ${{ inputs.process-group-id }}
        NIFI_PARAMETERS: ${{ inputs.parameters }}
        NIFI_LOG_LEVEL: ${{ inputs.log-level }}
        # Stop/Cleanup options
        NIFI_DISABLE_CONTROLLERS: ${{ inputs.disable-controllers }}
        NIFI_DELETE_PARAMETER_CONTEXT: ${{ inputs.delete-parameter-context }}
        NIFI_FORCE_DELETE: ${{ inputs.force }}
        # Export/Import options
        NIFI_EXPORT_FILE_PATH: ${{ inputs.file-path }}
        NIFI_FLOW_FILE_PATH: ${{ inputs.file-path }}
        NIFI_PARENT_ID: ${{ inputs.parent-id }}
        NIFI_EXPORT_MODE: ${{ inputs.export-mode }}
        # List registry flows options
        NIFI_DETAILED: ${{ inputs.detailed }}
      run: |
        set -e

        # Map command names to CLI function names
        case "${{ inputs.command }}" in
          ensure-registry)  CMD="ensure_registry" ;;
          deploy-flow)      CMD="deploy_flow" ;;
          start-flow)       CMD="start_flow" ;;
          stop-flow)        CMD="stop_flow" ;;
          get-status)       CMD="get_status" ;;
          configure-params) CMD="configure_params" ;;
          change-version)   CMD="change_flow_version" ;;
          revert-flow)      CMD="revert_flow" ;;
          cleanup)          CMD="cleanup" ;;
          purge-flowfiles)  CMD="purge_flowfiles" ;;
          export-flow-definition) CMD="export_flow_definition" ;;
          import-flow-definition) CMD="import_flow_definition" ;;
          list-registry-flows)    CMD="list_registry_flows" ;;
          get-versions)           CMD="get_flow_versions" ;;
          get-diff)               CMD="get_flow_diff" ;;
          *)
            echo "Unknown command: ${{ inputs.command }}"
            exit 1
            ;;
        esac

        echo "Running: nipyapi ci $CMD"

        # Run the CLI command - it auto-detects GitHub Actions and outputs in github format
        # CLI uses heredoc syntax for multiline values (like logs)
        OUTPUT=$(nipyapi ci $CMD 2>&1) || {
          echo "Command failed:"
          echo "$OUTPUT"
          exit 1
        }

        # Write outputs to GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "success=true" >> $GITHUB_OUTPUT

        # Show summary to console
        echo "$OUTPUT"

branding:
  icon: 'database'
  color: 'blue'
