#!/usr/bin/env python3
"""
Generate .secrets file for act testing by reading configuration from nipyapi repo.

This script reads the Docker Compose configuration from the nipyapi repository
and extracts the credentials for the github-cicd profile, ensuring we don't
duplicate configuration values.
"""
import os
import sys
import re
from pathlib import Path

def find_nipyapi_repo():
    """Find the nipyapi repository path."""
    # Check environment variable first
    nipyapi_infra = os.environ.get('NIPYAPI_INFRA', '../nipyapi')
    path = Path(nipyapi_infra).resolve()

    if not path.exists():
        print(f"ERROR: nipyapi repo not found at {path}", file=sys.stderr)
        print("Set NIPYAPI_INFRA environment variable to the correct path", file=sys.stderr)
        sys.exit(1)

    return path


def extract_compose_credentials(nipyapi_path):
    """Extract credentials from compose.yml for nifi-github service."""
    compose_file = nipyapi_path / 'resources' / 'docker' / 'compose.yml'

    if not compose_file.exists():
        print(f"ERROR: compose.yml not found at {compose_file}", file=sys.stderr)
        sys.exit(1)

    content = compose_file.read_text()

    # Extract credentials from nifi-github service section
    # Look for SINGLE_USER_CREDENTIALS_USERNAME and SINGLE_USER_CREDENTIALS_PASSWORD
    username_match = re.search(r'SINGLE_USER_CREDENTIALS_USERNAME[=:](\S+)', content)
    password_match = re.search(r'SINGLE_USER_CREDENTIALS_PASSWORD[=:](\S+)', content)

    if not username_match or not password_match:
        print("ERROR: Could not extract credentials from compose.yml", file=sys.stderr)
        sys.exit(1)

    return {
        'username': username_match.group(1),
        'password': password_match.group(1)
    }


def get_github_token():
    """Get GitHub registry token from environment or .env file."""
    # Check environment first
    token = os.environ.get('GH_REGISTRY_TOKEN')
    if token:
        return token

    # Check nipyapi .env file
    nipyapi_path = find_nipyapi_repo()
    env_file = nipyapi_path / '.env'
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            if line.startswith('GH_REGISTRY_TOKEN='):
                return line.split('=', 1)[1].strip()

    print("ERROR: GH_REGISTRY_TOKEN not found in environment or nipyapi/.env", file=sys.stderr)
    sys.exit(1)


def generate_secrets_file(output_path='.secrets'):
    """Generate the .secrets file for act."""
    nipyapi_path = find_nipyapi_repo()
    creds = extract_compose_credentials(nipyapi_path)
    token = get_github_token()

    # For act, we need host.docker.internal to reach the host from inside the container
    secrets_content = f"""# Generated by scripts/generate_secrets.py
# Source: {nipyapi_path}/resources/docker/compose.yml
NIFI_API_ENDPOINT=https://host.docker.internal:9447/nifi-api
NIFI_USERNAME={creds['username']}
NIFI_PASSWORD={creds['password']}
GH_REGISTRY_TOKEN={token}
FLOW_HTTP_ENDPOINT=http://host.docker.internal:8080
"""

    Path(output_path).write_text(secrets_content)
    print(f"Generated {output_path} with credentials from {nipyapi_path}")


if __name__ == '__main__':
    output = sys.argv[1] if len(sys.argv) > 1 else '.secrets'
    generate_secrets_file(output)
